/*
 * generated by Xtext 2.10.0
 */
package fr.enseeiht.gls.projet404.parser.antlr;

import com.google.inject.Inject;
import fr.enseeiht.gls.projet404.parser.antlr.internal.InternalGamesParser;
import fr.enseeiht.gls.projet404.services.GamesGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class GamesParser extends AbstractAntlrParser {

	@Inject
	private GamesGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalGamesParser createParser(XtextTokenStream stream) {
		return new InternalGamesParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Game";
	}

	public GamesGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(GamesGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
