/**
 * generated by Xtext 2.10.0
 */
package fr.enseeiht.gls.projet404.validation;

import fr.enseeiht.gls.projet404.validation.AbstractGamesValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class GamesValidator extends AbstractGamesValidator {
}
