/*
 * generated by Xtext 2.10.0
 */
package fr.enseeiht.gls.projet404.ui;

import com.google.inject.Injector;
import fr.enseeiht.gls.projet404.games.ui.internal.GamesActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class GamesExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return GamesActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return GamesActivator.getInstance().getInjector(GamesActivator.FR_ENSEEIHT_GLS_PROJET404_GAMES);
	}
	
}
