/**
 * generated by Xtext 2.10.0
 */
package fr.enseeiht.gls.projet404.ui.contentassist;

import fr.enseeiht.gls.projet404.ui.contentassist.AbstractGamesProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class GamesProposalProvider extends AbstractGamesProposalProvider {
}
