/*
 * generated by Xtext 2.10.0
 */
package fr.enseeiht.gls.projet404.ui.tests;

import com.google.inject.Injector;
import fr.enseeiht.gls.projet404.games.ui.internal.GamesActivator;
import org.eclipse.xtext.junit4.IInjectorProvider;

public class GamesUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return GamesActivator.getInstance().getInjector("fr.enseeiht.gls.projet404.Games");
	}

}
