/**
 * generated by Xtext 2.10.0
 */
package fr.enseeiht.gls.projet404.ui;

import fr.enseeiht.gls.projet404.ui.AbstractGamesUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class GamesUiModule extends AbstractGamesUiModule {
  public GamesUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
