/**
 * generated by Xtext 2.10.0
 */
package fr.enseeiht.gls.projet404;

import fr.enseeiht.gls.projet404.GamesStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class GamesStandaloneSetup extends GamesStandaloneSetupGenerated {
  public static void doSetup() {
    GamesStandaloneSetup _gamesStandaloneSetup = new GamesStandaloneSetup();
    _gamesStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
