/**
 * generated by Xtext 2.10.0
 */
package fr.enseeiht.gls.projet404;

import fr.enseeiht.gls.projet404.AbstractGamesRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class GamesRuntimeModule extends AbstractGamesRuntimeModule {
}
