/**
 * generated by Xtext 2.10.0
 */
package fr.enseeiht.gls.projet404.games;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Action</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.enseeiht.gls.projet404.games.Action#getName <em>Name</em>}</li>
 *   <li>{@link fr.enseeiht.gls.projet404.games.Action#getVal <em>Val</em>}</li>
 *   <li>{@link fr.enseeiht.gls.projet404.games.Action#getInterSuivante <em>Inter Suivante</em>}</li>
 *   <li>{@link fr.enseeiht.gls.projet404.games.Action#getKnowledgeGiven <em>Knowledge Given</em>}</li>
 *   <li>{@link fr.enseeiht.gls.projet404.games.Action#getItemsGiven <em>Items Given</em>}</li>
 *   <li>{@link fr.enseeiht.gls.projet404.games.Action#getItemsConsumed <em>Items Consumed</em>}</li>
 *   <li>{@link fr.enseeiht.gls.projet404.games.Action#getConditionsActionsAvailable <em>Conditions Actions Available</em>}</li>
 *   <li>{@link fr.enseeiht.gls.projet404.games.Action#getGame <em>Game</em>}</li>
 * </ul>
 *
 * @see fr.enseeiht.gls.projet404.games.GamesPackage#getAction()
 * @model
 * @generated
 */
public interface Action extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see fr.enseeiht.gls.projet404.games.GamesPackage#getAction_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link fr.enseeiht.gls.projet404.games.Action#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Val</b></em>' attribute.
   * The literals are from the enumeration {@link fr.enseeiht.gls.projet404.games.Actions}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Val</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Val</em>' attribute.
   * @see fr.enseeiht.gls.projet404.games.Actions
   * @see #setVal(Actions)
   * @see fr.enseeiht.gls.projet404.games.GamesPackage#getAction_Val()
   * @model
   * @generated
   */
  Actions getVal();

  /**
   * Sets the value of the '{@link fr.enseeiht.gls.projet404.games.Action#getVal <em>Val</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Val</em>' attribute.
   * @see fr.enseeiht.gls.projet404.games.Actions
   * @see #getVal()
   * @generated
   */
  void setVal(Actions value);

  /**
   * Returns the value of the '<em><b>Inter Suivante</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Inter Suivante</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Inter Suivante</em>' containment reference.
   * @see #setInterSuivante(Interaction)
   * @see fr.enseeiht.gls.projet404.games.GamesPackage#getAction_InterSuivante()
   * @model containment="true"
   * @generated
   */
  Interaction getInterSuivante();

  /**
   * Sets the value of the '{@link fr.enseeiht.gls.projet404.games.Action#getInterSuivante <em>Inter Suivante</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Inter Suivante</em>' containment reference.
   * @see #getInterSuivante()
   * @generated
   */
  void setInterSuivante(Interaction value);

  /**
   * Returns the value of the '<em><b>Knowledge Given</b></em>' reference list.
   * The list contents are of type {@link fr.enseeiht.gls.projet404.games.Knowledge}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Knowledge Given</em>' reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Knowledge Given</em>' reference list.
   * @see fr.enseeiht.gls.projet404.games.GamesPackage#getAction_KnowledgeGiven()
   * @model
   * @generated
   */
  EList<Knowledge> getKnowledgeGiven();

  /**
   * Returns the value of the '<em><b>Items Given</b></em>' containment reference list.
   * The list contents are of type {@link fr.enseeiht.gls.projet404.games.ItemInSomething}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Items Given</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Items Given</em>' containment reference list.
   * @see fr.enseeiht.gls.projet404.games.GamesPackage#getAction_ItemsGiven()
   * @model containment="true"
   * @generated
   */
  EList<ItemInSomething> getItemsGiven();

  /**
   * Returns the value of the '<em><b>Items Consumed</b></em>' containment reference list.
   * The list contents are of type {@link fr.enseeiht.gls.projet404.games.ItemInSomething}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Items Consumed</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Items Consumed</em>' containment reference list.
   * @see fr.enseeiht.gls.projet404.games.GamesPackage#getAction_ItemsConsumed()
   * @model containment="true"
   * @generated
   */
  EList<ItemInSomething> getItemsConsumed();

  /**
   * Returns the value of the '<em><b>Conditions Actions Available</b></em>' containment reference list.
   * The list contents are of type {@link fr.enseeiht.gls.projet404.games.Condition}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Conditions Actions Available</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Conditions Actions Available</em>' containment reference list.
   * @see fr.enseeiht.gls.projet404.games.GamesPackage#getAction_ConditionsActionsAvailable()
   * @model containment="true"
   * @generated
   */
  EList<Condition> getConditionsActionsAvailable();

  /**
   * Returns the value of the '<em><b>Game</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Game</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Game</em>' reference.
   * @see #setGame(Game)
   * @see fr.enseeiht.gls.projet404.games.GamesPackage#getAction_Game()
   * @model
   * @generated
   */
  Game getGame();

  /**
   * Sets the value of the '{@link fr.enseeiht.gls.projet404.games.Action#getGame <em>Game</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Game</em>' reference.
   * @see #getGame()
   * @generated
   */
  void setGame(Game value);

} // Action
