/**
 * generated by Xtext 2.10.0
 */
package fr.enseeiht.gls.projet404.games;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Condition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.enseeiht.gls.projet404.games.Condition#getName <em>Name</em>}</li>
 *   <li>{@link fr.enseeiht.gls.projet404.games.Condition#getPlayer <em>Player</em>}</li>
 *   <li>{@link fr.enseeiht.gls.projet404.games.Condition#getKnow <em>Know</em>}</li>
 *   <li>{@link fr.enseeiht.gls.projet404.games.Condition#getItem <em>Item</em>}</li>
 * </ul>
 *
 * @see fr.enseeiht.gls.projet404.games.GamesPackage#getCondition()
 * @model
 * @generated
 */
public interface Condition extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see fr.enseeiht.gls.projet404.games.GamesPackage#getCondition_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link fr.enseeiht.gls.projet404.games.Condition#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Player</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Player</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Player</em>' reference.
   * @see #setPlayer(Player)
   * @see fr.enseeiht.gls.projet404.games.GamesPackage#getCondition_Player()
   * @model
   * @generated
   */
  Player getPlayer();

  /**
   * Sets the value of the '{@link fr.enseeiht.gls.projet404.games.Condition#getPlayer <em>Player</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Player</em>' reference.
   * @see #getPlayer()
   * @generated
   */
  void setPlayer(Player value);

  /**
   * Returns the value of the '<em><b>Know</b></em>' reference list.
   * The list contents are of type {@link fr.enseeiht.gls.projet404.games.Knowledge}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Know</em>' reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Know</em>' reference list.
   * @see fr.enseeiht.gls.projet404.games.GamesPackage#getCondition_Know()
   * @model
   * @generated
   */
  EList<Knowledge> getKnow();

  /**
   * Returns the value of the '<em><b>Item</b></em>' containment reference list.
   * The list contents are of type {@link fr.enseeiht.gls.projet404.games.ItemInCondition}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Item</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Item</em>' containment reference list.
   * @see fr.enseeiht.gls.projet404.games.GamesPackage#getCondition_Item()
   * @model containment="true"
   * @generated
   */
  EList<ItemInCondition> getItem();

} // Condition
