/**
 * generated by Xtext 2.10.0
 */
package fr.enseeiht.gls.projet404.games;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Difficulty</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.enseeiht.gls.projet404.games.Difficulty#getLvl <em>Lvl</em>}</li>
 *   <li>{@link fr.enseeiht.gls.projet404.games.Difficulty#getSizeMax <em>Size Max</em>}</li>
 *   <li>{@link fr.enseeiht.gls.projet404.games.Difficulty#getItems <em>Items</em>}</li>
 *   <li>{@link fr.enseeiht.gls.projet404.games.Difficulty#getKnowledges <em>Knowledges</em>}</li>
 * </ul>
 *
 * @see fr.enseeiht.gls.projet404.games.GamesPackage#getDifficulty()
 * @model
 * @generated
 */
public interface Difficulty extends EObject
{
  /**
   * Returns the value of the '<em><b>Lvl</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Lvl</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Lvl</em>' attribute.
   * @see #setLvl(int)
   * @see fr.enseeiht.gls.projet404.games.GamesPackage#getDifficulty_Lvl()
   * @model
   * @generated
   */
  int getLvl();

  /**
   * Sets the value of the '{@link fr.enseeiht.gls.projet404.games.Difficulty#getLvl <em>Lvl</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Lvl</em>' attribute.
   * @see #getLvl()
   * @generated
   */
  void setLvl(int value);

  /**
   * Returns the value of the '<em><b>Size Max</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Size Max</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Size Max</em>' attribute.
   * @see #setSizeMax(int)
   * @see fr.enseeiht.gls.projet404.games.GamesPackage#getDifficulty_SizeMax()
   * @model
   * @generated
   */
  int getSizeMax();

  /**
   * Sets the value of the '{@link fr.enseeiht.gls.projet404.games.Difficulty#getSizeMax <em>Size Max</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Size Max</em>' attribute.
   * @see #getSizeMax()
   * @generated
   */
  void setSizeMax(int value);

  /**
   * Returns the value of the '<em><b>Items</b></em>' containment reference list.
   * The list contents are of type {@link fr.enseeiht.gls.projet404.games.ItemInSomething}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Items</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Items</em>' containment reference list.
   * @see fr.enseeiht.gls.projet404.games.GamesPackage#getDifficulty_Items()
   * @model containment="true"
   * @generated
   */
  EList<ItemInSomething> getItems();

  /**
   * Returns the value of the '<em><b>Knowledges</b></em>' reference list.
   * The list contents are of type {@link fr.enseeiht.gls.projet404.games.Knowledge}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Knowledges</em>' reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Knowledges</em>' reference list.
   * @see fr.enseeiht.gls.projet404.games.GamesPackage#getDifficulty_Knowledges()
   * @model
   * @generated
   */
  EList<Knowledge> getKnowledges();

} // Difficulty
