/**
 * generated by Xtext 2.10.0
 */
package fr.enseeiht.gls.projet404.games;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Element Jeu Fact</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.enseeiht.gls.projet404.games.ElementJeuFact#getDescription <em>Description</em>}</li>
 *   <li>{@link fr.enseeiht.gls.projet404.games.ElementJeuFact#getVisible <em>Visible</em>}</li>
 *   <li>{@link fr.enseeiht.gls.projet404.games.ElementJeuFact#getCond <em>Cond</em>}</li>
 * </ul>
 *
 * @see fr.enseeiht.gls.projet404.games.GamesPackage#getElementJeuFact()
 * @model
 * @generated
 */
public interface ElementJeuFact extends EObject
{
  /**
   * Returns the value of the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Description</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Description</em>' attribute.
   * @see #setDescription(String)
   * @see fr.enseeiht.gls.projet404.games.GamesPackage#getElementJeuFact_Description()
   * @model
   * @generated
   */
  String getDescription();

  /**
   * Sets the value of the '{@link fr.enseeiht.gls.projet404.games.ElementJeuFact#getDescription <em>Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Description</em>' attribute.
   * @see #getDescription()
   * @generated
   */
  void setDescription(String value);

  /**
   * Returns the value of the '<em><b>Visible</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Visible</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Visible</em>' attribute.
   * @see #setVisible(int)
   * @see fr.enseeiht.gls.projet404.games.GamesPackage#getElementJeuFact_Visible()
   * @model
   * @generated
   */
  int getVisible();

  /**
   * Sets the value of the '{@link fr.enseeiht.gls.projet404.games.ElementJeuFact#getVisible <em>Visible</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Visible</em>' attribute.
   * @see #getVisible()
   * @generated
   */
  void setVisible(int value);

  /**
   * Returns the value of the '<em><b>Cond</b></em>' containment reference list.
   * The list contents are of type {@link fr.enseeiht.gls.projet404.games.Condition}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Cond</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cond</em>' containment reference list.
   * @see fr.enseeiht.gls.projet404.games.GamesPackage#getElementJeuFact_Cond()
   * @model containment="true"
   * @generated
   */
  EList<Condition> getCond();

} // ElementJeuFact
