/**
 * generated by Xtext 2.10.0
 */
package fr.enseeiht.gls.projet404.games;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Game</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.enseeiht.gls.projet404.games.Game#getName <em>Name</em>}</li>
 *   <li>{@link fr.enseeiht.gls.projet404.games.Game#getPlayer <em>Player</em>}</li>
 *   <li>{@link fr.enseeiht.gls.projet404.games.Game#getPlaces <em>Places</em>}</li>
 *   <li>{@link fr.enseeiht.gls.projet404.games.Game#getKnowledge <em>Knowledge</em>}</li>
 *   <li>{@link fr.enseeiht.gls.projet404.games.Game#getPeople <em>People</em>}</li>
 *   <li>{@link fr.enseeiht.gls.projet404.games.Game#getItems <em>Items</em>}</li>
 *   <li>{@link fr.enseeiht.gls.projet404.games.Game#getPath <em>Path</em>}</li>
 *   <li>{@link fr.enseeiht.gls.projet404.games.Game#getRecipes <em>Recipes</em>}</li>
 *   <li>{@link fr.enseeiht.gls.projet404.games.Game#getStartPlace <em>Start Place</em>}</li>
 *   <li>{@link fr.enseeiht.gls.projet404.games.Game#getEndPlace <em>End Place</em>}</li>
 *   <li>{@link fr.enseeiht.gls.projet404.games.Game#getDifficulty <em>Difficulty</em>}</li>
 * </ul>
 *
 * @see fr.enseeiht.gls.projet404.games.GamesPackage#getGame()
 * @model
 * @generated
 */
public interface Game extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see fr.enseeiht.gls.projet404.games.GamesPackage#getGame_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link fr.enseeiht.gls.projet404.games.Game#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Player</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Player</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Player</em>' containment reference.
   * @see #setPlayer(Player)
   * @see fr.enseeiht.gls.projet404.games.GamesPackage#getGame_Player()
   * @model containment="true"
   * @generated
   */
  Player getPlayer();

  /**
   * Sets the value of the '{@link fr.enseeiht.gls.projet404.games.Game#getPlayer <em>Player</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Player</em>' containment reference.
   * @see #getPlayer()
   * @generated
   */
  void setPlayer(Player value);

  /**
   * Returns the value of the '<em><b>Places</b></em>' containment reference list.
   * The list contents are of type {@link fr.enseeiht.gls.projet404.games.Place}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Places</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Places</em>' containment reference list.
   * @see fr.enseeiht.gls.projet404.games.GamesPackage#getGame_Places()
   * @model containment="true"
   * @generated
   */
  EList<Place> getPlaces();

  /**
   * Returns the value of the '<em><b>Knowledge</b></em>' containment reference list.
   * The list contents are of type {@link fr.enseeiht.gls.projet404.games.Knowledge}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Knowledge</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Knowledge</em>' containment reference list.
   * @see fr.enseeiht.gls.projet404.games.GamesPackage#getGame_Knowledge()
   * @model containment="true"
   * @generated
   */
  EList<Knowledge> getKnowledge();

  /**
   * Returns the value of the '<em><b>People</b></em>' containment reference list.
   * The list contents are of type {@link fr.enseeiht.gls.projet404.games.People}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>People</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>People</em>' containment reference list.
   * @see fr.enseeiht.gls.projet404.games.GamesPackage#getGame_People()
   * @model containment="true"
   * @generated
   */
  EList<People> getPeople();

  /**
   * Returns the value of the '<em><b>Items</b></em>' containment reference list.
   * The list contents are of type {@link fr.enseeiht.gls.projet404.games.Item}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Items</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Items</em>' containment reference list.
   * @see fr.enseeiht.gls.projet404.games.GamesPackage#getGame_Items()
   * @model containment="true"
   * @generated
   */
  EList<Item> getItems();

  /**
   * Returns the value of the '<em><b>Path</b></em>' containment reference list.
   * The list contents are of type {@link fr.enseeiht.gls.projet404.games.Path}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Path</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Path</em>' containment reference list.
   * @see fr.enseeiht.gls.projet404.games.GamesPackage#getGame_Path()
   * @model containment="true"
   * @generated
   */
  EList<Path> getPath();

  /**
   * Returns the value of the '<em><b>Recipes</b></em>' containment reference list.
   * The list contents are of type {@link fr.enseeiht.gls.projet404.games.Recipe}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Recipes</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Recipes</em>' containment reference list.
   * @see fr.enseeiht.gls.projet404.games.GamesPackage#getGame_Recipes()
   * @model containment="true"
   * @generated
   */
  EList<Recipe> getRecipes();

  /**
   * Returns the value of the '<em><b>Start Place</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Start Place</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Start Place</em>' reference.
   * @see #setStartPlace(Place)
   * @see fr.enseeiht.gls.projet404.games.GamesPackage#getGame_StartPlace()
   * @model
   * @generated
   */
  Place getStartPlace();

  /**
   * Sets the value of the '{@link fr.enseeiht.gls.projet404.games.Game#getStartPlace <em>Start Place</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Start Place</em>' reference.
   * @see #getStartPlace()
   * @generated
   */
  void setStartPlace(Place value);

  /**
   * Returns the value of the '<em><b>End Place</b></em>' reference list.
   * The list contents are of type {@link fr.enseeiht.gls.projet404.games.Place}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>End Place</em>' reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>End Place</em>' reference list.
   * @see fr.enseeiht.gls.projet404.games.GamesPackage#getGame_EndPlace()
   * @model
   * @generated
   */
  EList<Place> getEndPlace();

  /**
   * Returns the value of the '<em><b>Difficulty</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Difficulty</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Difficulty</em>' containment reference.
   * @see #setDifficulty(Difficulty)
   * @see fr.enseeiht.gls.projet404.games.GamesPackage#getGame_Difficulty()
   * @model containment="true"
   * @generated
   */
  Difficulty getDifficulty();

  /**
   * Sets the value of the '{@link fr.enseeiht.gls.projet404.games.Game#getDifficulty <em>Difficulty</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Difficulty</em>' containment reference.
   * @see #getDifficulty()
   * @generated
   */
  void setDifficulty(Difficulty value);

} // Game
