/**
 * generated by Xtext 2.10.0
 */
package fr.enseeiht.gls.projet404.games;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Interaction</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.enseeiht.gls.projet404.games.Interaction#getName <em>Name</em>}</li>
 *   <li>{@link fr.enseeiht.gls.projet404.games.Interaction#getProp <em>Prop</em>}</li>
 *   <li>{@link fr.enseeiht.gls.projet404.games.Interaction#getConditionsBegin <em>Conditions Begin</em>}</li>
 *   <li>{@link fr.enseeiht.gls.projet404.games.Interaction#getConditionsEnd <em>Conditions End</em>}</li>
 * </ul>
 *
 * @see fr.enseeiht.gls.projet404.games.GamesPackage#getInteraction()
 * @model
 * @generated
 */
public interface Interaction extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see fr.enseeiht.gls.projet404.games.GamesPackage#getInteraction_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link fr.enseeiht.gls.projet404.games.Interaction#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Prop</b></em>' containment reference list.
   * The list contents are of type {@link fr.enseeiht.gls.projet404.games.Proposition}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Prop</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Prop</em>' containment reference list.
   * @see fr.enseeiht.gls.projet404.games.GamesPackage#getInteraction_Prop()
   * @model containment="true"
   * @generated
   */
  EList<Proposition> getProp();

  /**
   * Returns the value of the '<em><b>Conditions Begin</b></em>' containment reference list.
   * The list contents are of type {@link fr.enseeiht.gls.projet404.games.Condition}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Conditions Begin</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Conditions Begin</em>' containment reference list.
   * @see fr.enseeiht.gls.projet404.games.GamesPackage#getInteraction_ConditionsBegin()
   * @model containment="true"
   * @generated
   */
  EList<Condition> getConditionsBegin();

  /**
   * Returns the value of the '<em><b>Conditions End</b></em>' containment reference list.
   * The list contents are of type {@link fr.enseeiht.gls.projet404.games.Condition}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Conditions End</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Conditions End</em>' containment reference list.
   * @see fr.enseeiht.gls.projet404.games.GamesPackage#getInteraction_ConditionsEnd()
   * @model containment="true"
   * @generated
   */
  EList<Condition> getConditionsEnd();

} // Interaction
