/**
 * generated by Xtext 2.10.0
 */
package fr.enseeiht.gls.projet404.games;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Knowledge</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.enseeiht.gls.projet404.games.Knowledge#getName <em>Name</em>}</li>
 *   <li>{@link fr.enseeiht.gls.projet404.games.Knowledge#getDescription <em>Description</em>}</li>
 *   <li>{@link fr.enseeiht.gls.projet404.games.Knowledge#getVisible <em>Visible</em>}</li>
 *   <li>{@link fr.enseeiht.gls.projet404.games.Knowledge#getConditionsVisible <em>Conditions Visible</em>}</li>
 *   <li>{@link fr.enseeiht.gls.projet404.games.Knowledge#getActive <em>Active</em>}</li>
 *   <li>{@link fr.enseeiht.gls.projet404.games.Knowledge#getConditionsActive <em>Conditions Active</em>}</li>
 *   <li>{@link fr.enseeiht.gls.projet404.games.Knowledge#getConditionsGive <em>Conditions Give</em>}</li>
 * </ul>
 *
 * @see fr.enseeiht.gls.projet404.games.GamesPackage#getKnowledge()
 * @model
 * @generated
 */
public interface Knowledge extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see fr.enseeiht.gls.projet404.games.GamesPackage#getKnowledge_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link fr.enseeiht.gls.projet404.games.Knowledge#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Description</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Description</em>' attribute.
   * @see #setDescription(String)
   * @see fr.enseeiht.gls.projet404.games.GamesPackage#getKnowledge_Description()
   * @model
   * @generated
   */
  String getDescription();

  /**
   * Sets the value of the '{@link fr.enseeiht.gls.projet404.games.Knowledge#getDescription <em>Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Description</em>' attribute.
   * @see #getDescription()
   * @generated
   */
  void setDescription(String value);

  /**
   * Returns the value of the '<em><b>Visible</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Visible</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Visible</em>' attribute.
   * @see #setVisible(int)
   * @see fr.enseeiht.gls.projet404.games.GamesPackage#getKnowledge_Visible()
   * @model
   * @generated
   */
  int getVisible();

  /**
   * Sets the value of the '{@link fr.enseeiht.gls.projet404.games.Knowledge#getVisible <em>Visible</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Visible</em>' attribute.
   * @see #getVisible()
   * @generated
   */
  void setVisible(int value);

  /**
   * Returns the value of the '<em><b>Conditions Visible</b></em>' containment reference list.
   * The list contents are of type {@link fr.enseeiht.gls.projet404.games.Condition}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Conditions Visible</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Conditions Visible</em>' containment reference list.
   * @see fr.enseeiht.gls.projet404.games.GamesPackage#getKnowledge_ConditionsVisible()
   * @model containment="true"
   * @generated
   */
  EList<Condition> getConditionsVisible();

  /**
   * Returns the value of the '<em><b>Active</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Active</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Active</em>' attribute.
   * @see #setActive(int)
   * @see fr.enseeiht.gls.projet404.games.GamesPackage#getKnowledge_Active()
   * @model
   * @generated
   */
  int getActive();

  /**
   * Sets the value of the '{@link fr.enseeiht.gls.projet404.games.Knowledge#getActive <em>Active</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Active</em>' attribute.
   * @see #getActive()
   * @generated
   */
  void setActive(int value);

  /**
   * Returns the value of the '<em><b>Conditions Active</b></em>' containment reference list.
   * The list contents are of type {@link fr.enseeiht.gls.projet404.games.Condition}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Conditions Active</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Conditions Active</em>' containment reference list.
   * @see fr.enseeiht.gls.projet404.games.GamesPackage#getKnowledge_ConditionsActive()
   * @model containment="true"
   * @generated
   */
  EList<Condition> getConditionsActive();

  /**
   * Returns the value of the '<em><b>Conditions Give</b></em>' containment reference list.
   * The list contents are of type {@link fr.enseeiht.gls.projet404.games.Condition}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Conditions Give</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Conditions Give</em>' containment reference list.
   * @see fr.enseeiht.gls.projet404.games.GamesPackage#getKnowledge_ConditionsGive()
   * @model containment="true"
   * @generated
   */
  EList<Condition> getConditionsGive();

} // Knowledge
