/**
 * generated by Xtext 2.10.0
 */
package fr.enseeiht.gls.projet404.games;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Object In Condition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.enseeiht.gls.projet404.games.ObjectInCondition#getObject <em>Object</em>}</li>
 *   <li>{@link fr.enseeiht.gls.projet404.games.ObjectInCondition#getQuantity <em>Quantity</em>}</li>
 * </ul>
 *
 * @see fr.enseeiht.gls.projet404.games.GamesPackage#getObjectInCondition()
 * @model
 * @generated
 */
public interface ObjectInCondition extends EObject
{
  /**
   * Returns the value of the '<em><b>Object</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Object</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Object</em>' reference.
   * @see #setObject(fr.enseeiht.gls.projet404.games.Object)
   * @see fr.enseeiht.gls.projet404.games.GamesPackage#getObjectInCondition_Object()
   * @model
   * @generated
   */
  fr.enseeiht.gls.projet404.games.Object getObject();

  /**
   * Sets the value of the '{@link fr.enseeiht.gls.projet404.games.ObjectInCondition#getObject <em>Object</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Object</em>' reference.
   * @see #getObject()
   * @generated
   */
  void setObject(fr.enseeiht.gls.projet404.games.Object value);

  /**
   * Returns the value of the '<em><b>Quantity</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Quantity</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Quantity</em>' attribute.
   * @see #setQuantity(int)
   * @see fr.enseeiht.gls.projet404.games.GamesPackage#getObjectInCondition_Quantity()
   * @model
   * @generated
   */
  int getQuantity();

  /**
   * Sets the value of the '{@link fr.enseeiht.gls.projet404.games.ObjectInCondition#getQuantity <em>Quantity</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Quantity</em>' attribute.
   * @see #getQuantity()
   * @generated
   */
  void setQuantity(int value);

} // ObjectInCondition
