/**
 * generated by Xtext 2.10.0
 */
package fr.enseeiht.gls.projet404.games;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Path</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.enseeiht.gls.projet404.games.Path#getName <em>Name</em>}</li>
 *   <li>{@link fr.enseeiht.gls.projet404.games.Path#getDescription <em>Description</em>}</li>
 *   <li>{@link fr.enseeiht.gls.projet404.games.Path#getVisible <em>Visible</em>}</li>
 *   <li>{@link fr.enseeiht.gls.projet404.games.Path#getConditionVisible <em>Condition Visible</em>}</li>
 *   <li>{@link fr.enseeiht.gls.projet404.games.Path#getEndPlace <em>End Place</em>}</li>
 *   <li>{@link fr.enseeiht.gls.projet404.games.Path#getIsOpen <em>Is Open</em>}</li>
 *   <li>{@link fr.enseeiht.gls.projet404.games.Path#getConditionsOpening <em>Conditions Opening</em>}</li>
 *   <li>{@link fr.enseeiht.gls.projet404.games.Path#getIsMandatory <em>Is Mandatory</em>}</li>
 *   <li>{@link fr.enseeiht.gls.projet404.games.Path#getKnowledgeGiven <em>Knowledge Given</em>}</li>
 *   <li>{@link fr.enseeiht.gls.projet404.games.Path#getItemsGiven <em>Items Given</em>}</li>
 *   <li>{@link fr.enseeiht.gls.projet404.games.Path#getItemsConsumed <em>Items Consumed</em>}</li>
 * </ul>
 *
 * @see fr.enseeiht.gls.projet404.games.GamesPackage#getPath()
 * @model
 * @generated
 */
public interface Path extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see fr.enseeiht.gls.projet404.games.GamesPackage#getPath_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link fr.enseeiht.gls.projet404.games.Path#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Description</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Description</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Description</em>' attribute.
   * @see #setDescription(String)
   * @see fr.enseeiht.gls.projet404.games.GamesPackage#getPath_Description()
   * @model
   * @generated
   */
  String getDescription();

  /**
   * Sets the value of the '{@link fr.enseeiht.gls.projet404.games.Path#getDescription <em>Description</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Description</em>' attribute.
   * @see #getDescription()
   * @generated
   */
  void setDescription(String value);

  /**
   * Returns the value of the '<em><b>Visible</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Visible</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Visible</em>' attribute.
   * @see #setVisible(int)
   * @see fr.enseeiht.gls.projet404.games.GamesPackage#getPath_Visible()
   * @model
   * @generated
   */
  int getVisible();

  /**
   * Sets the value of the '{@link fr.enseeiht.gls.projet404.games.Path#getVisible <em>Visible</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Visible</em>' attribute.
   * @see #getVisible()
   * @generated
   */
  void setVisible(int value);

  /**
   * Returns the value of the '<em><b>Condition Visible</b></em>' containment reference list.
   * The list contents are of type {@link fr.enseeiht.gls.projet404.games.Condition}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Condition Visible</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Condition Visible</em>' containment reference list.
   * @see fr.enseeiht.gls.projet404.games.GamesPackage#getPath_ConditionVisible()
   * @model containment="true"
   * @generated
   */
  EList<Condition> getConditionVisible();

  /**
   * Returns the value of the '<em><b>End Place</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>End Place</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>End Place</em>' reference.
   * @see #setEndPlace(Place)
   * @see fr.enseeiht.gls.projet404.games.GamesPackage#getPath_EndPlace()
   * @model
   * @generated
   */
  Place getEndPlace();

  /**
   * Sets the value of the '{@link fr.enseeiht.gls.projet404.games.Path#getEndPlace <em>End Place</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>End Place</em>' reference.
   * @see #getEndPlace()
   * @generated
   */
  void setEndPlace(Place value);

  /**
   * Returns the value of the '<em><b>Is Open</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Is Open</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Is Open</em>' attribute.
   * @see #setIsOpen(int)
   * @see fr.enseeiht.gls.projet404.games.GamesPackage#getPath_IsOpen()
   * @model
   * @generated
   */
  int getIsOpen();

  /**
   * Sets the value of the '{@link fr.enseeiht.gls.projet404.games.Path#getIsOpen <em>Is Open</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Is Open</em>' attribute.
   * @see #getIsOpen()
   * @generated
   */
  void setIsOpen(int value);

  /**
   * Returns the value of the '<em><b>Conditions Opening</b></em>' containment reference list.
   * The list contents are of type {@link fr.enseeiht.gls.projet404.games.Condition}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Conditions Opening</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Conditions Opening</em>' containment reference list.
   * @see fr.enseeiht.gls.projet404.games.GamesPackage#getPath_ConditionsOpening()
   * @model containment="true"
   * @generated
   */
  EList<Condition> getConditionsOpening();

  /**
   * Returns the value of the '<em><b>Is Mandatory</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Is Mandatory</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Is Mandatory</em>' attribute.
   * @see #setIsMandatory(int)
   * @see fr.enseeiht.gls.projet404.games.GamesPackage#getPath_IsMandatory()
   * @model
   * @generated
   */
  int getIsMandatory();

  /**
   * Sets the value of the '{@link fr.enseeiht.gls.projet404.games.Path#getIsMandatory <em>Is Mandatory</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Is Mandatory</em>' attribute.
   * @see #getIsMandatory()
   * @generated
   */
  void setIsMandatory(int value);

  /**
   * Returns the value of the '<em><b>Knowledge Given</b></em>' reference list.
   * The list contents are of type {@link fr.enseeiht.gls.projet404.games.Knowledge}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Knowledge Given</em>' reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Knowledge Given</em>' reference list.
   * @see fr.enseeiht.gls.projet404.games.GamesPackage#getPath_KnowledgeGiven()
   * @model
   * @generated
   */
  EList<Knowledge> getKnowledgeGiven();

  /**
   * Returns the value of the '<em><b>Items Given</b></em>' containment reference list.
   * The list contents are of type {@link fr.enseeiht.gls.projet404.games.ItemInSomething}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Items Given</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Items Given</em>' containment reference list.
   * @see fr.enseeiht.gls.projet404.games.GamesPackage#getPath_ItemsGiven()
   * @model containment="true"
   * @generated
   */
  EList<ItemInSomething> getItemsGiven();

  /**
   * Returns the value of the '<em><b>Items Consumed</b></em>' containment reference list.
   * The list contents are of type {@link fr.enseeiht.gls.projet404.games.ItemInSomething}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Items Consumed</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Items Consumed</em>' containment reference list.
   * @see fr.enseeiht.gls.projet404.games.GamesPackage#getPath_ItemsConsumed()
   * @model containment="true"
   * @generated
   */
  EList<ItemInSomething> getItemsConsumed();

} // Path
