/**
 * generated by Xtext 2.10.0
 */
package fr.enseeiht.gls.projet404.games;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Recipe</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.enseeiht.gls.projet404.games.Recipe#getName <em>Name</em>}</li>
 *   <li>{@link fr.enseeiht.gls.projet404.games.Recipe#getObjectsUsed <em>Objects Used</em>}</li>
 *   <li>{@link fr.enseeiht.gls.projet404.games.Recipe#getConditions <em>Conditions</em>}</li>
 *   <li>{@link fr.enseeiht.gls.projet404.games.Recipe#getItemsMade <em>Items Made</em>}</li>
 * </ul>
 *
 * @see fr.enseeiht.gls.projet404.games.GamesPackage#getRecipe()
 * @model
 * @generated
 */
public interface Recipe extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see fr.enseeiht.gls.projet404.games.GamesPackage#getRecipe_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link fr.enseeiht.gls.projet404.games.Recipe#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Objects Used</b></em>' containment reference list.
   * The list contents are of type {@link fr.enseeiht.gls.projet404.games.ItemInSomething}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Objects Used</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Objects Used</em>' containment reference list.
   * @see fr.enseeiht.gls.projet404.games.GamesPackage#getRecipe_ObjectsUsed()
   * @model containment="true"
   * @generated
   */
  EList<ItemInSomething> getObjectsUsed();

  /**
   * Returns the value of the '<em><b>Conditions</b></em>' containment reference list.
   * The list contents are of type {@link fr.enseeiht.gls.projet404.games.Condition}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Conditions</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Conditions</em>' containment reference list.
   * @see fr.enseeiht.gls.projet404.games.GamesPackage#getRecipe_Conditions()
   * @model containment="true"
   * @generated
   */
  EList<Condition> getConditions();

  /**
   * Returns the value of the '<em><b>Items Made</b></em>' containment reference list.
   * The list contents are of type {@link fr.enseeiht.gls.projet404.games.ItemInSomething}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Items Made</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Items Made</em>' containment reference list.
   * @see fr.enseeiht.gls.projet404.games.GamesPackage#getRecipe_ItemsMade()
   * @model containment="true"
   * @generated
   */
  EList<ItemInSomething> getItemsMade();

} // Recipe
