/*
 * generated by Xtext 2.10.0
 */
package fr.enseeiht.gls.projet404.scoping


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
class GamesScopeProvider extends AbstractGamesScopeProvider {

}
