/**
 * generated by Xtext 2.10.0
 */
package fr.enseeiht.gls.projet404.games.impl;

import fr.enseeiht.gls.projet404.games.Condition;
import fr.enseeiht.gls.projet404.games.GamesPackage;
import fr.enseeiht.gls.projet404.games.Interaction;
import fr.enseeiht.gls.projet404.games.Proposition;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Interaction</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link fr.enseeiht.gls.projet404.games.impl.InteractionImpl#getName <em>Name</em>}</li>
 *   <li>{@link fr.enseeiht.gls.projet404.games.impl.InteractionImpl#getProp <em>Prop</em>}</li>
 *   <li>{@link fr.enseeiht.gls.projet404.games.impl.InteractionImpl#getConditionsBegin <em>Conditions Begin</em>}</li>
 *   <li>{@link fr.enseeiht.gls.projet404.games.impl.InteractionImpl#getConditionsEnd <em>Conditions End</em>}</li>
 * </ul>
 *
 * @generated
 */
public class InteractionImpl extends MinimalEObjectImpl.Container implements Interaction
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getProp() <em>Prop</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getProp()
   * @generated
   * @ordered
   */
  protected EList<Proposition> prop;

  /**
   * The cached value of the '{@link #getConditionsBegin() <em>Conditions Begin</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getConditionsBegin()
   * @generated
   * @ordered
   */
  protected EList<Condition> conditionsBegin;

  /**
   * The cached value of the '{@link #getConditionsEnd() <em>Conditions End</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getConditionsEnd()
   * @generated
   * @ordered
   */
  protected EList<Condition> conditionsEnd;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected InteractionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GamesPackage.Literals.INTERACTION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GamesPackage.INTERACTION__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Proposition> getProp()
  {
    if (prop == null)
    {
      prop = new EObjectContainmentEList<Proposition>(Proposition.class, this, GamesPackage.INTERACTION__PROP);
    }
    return prop;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Condition> getConditionsBegin()
  {
    if (conditionsBegin == null)
    {
      conditionsBegin = new EObjectContainmentEList<Condition>(Condition.class, this, GamesPackage.INTERACTION__CONDITIONS_BEGIN);
    }
    return conditionsBegin;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Condition> getConditionsEnd()
  {
    if (conditionsEnd == null)
    {
      conditionsEnd = new EObjectContainmentEList<Condition>(Condition.class, this, GamesPackage.INTERACTION__CONDITIONS_END);
    }
    return conditionsEnd;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case GamesPackage.INTERACTION__PROP:
        return ((InternalEList<?>)getProp()).basicRemove(otherEnd, msgs);
      case GamesPackage.INTERACTION__CONDITIONS_BEGIN:
        return ((InternalEList<?>)getConditionsBegin()).basicRemove(otherEnd, msgs);
      case GamesPackage.INTERACTION__CONDITIONS_END:
        return ((InternalEList<?>)getConditionsEnd()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case GamesPackage.INTERACTION__NAME:
        return getName();
      case GamesPackage.INTERACTION__PROP:
        return getProp();
      case GamesPackage.INTERACTION__CONDITIONS_BEGIN:
        return getConditionsBegin();
      case GamesPackage.INTERACTION__CONDITIONS_END:
        return getConditionsEnd();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case GamesPackage.INTERACTION__NAME:
        setName((String)newValue);
        return;
      case GamesPackage.INTERACTION__PROP:
        getProp().clear();
        getProp().addAll((Collection<? extends Proposition>)newValue);
        return;
      case GamesPackage.INTERACTION__CONDITIONS_BEGIN:
        getConditionsBegin().clear();
        getConditionsBegin().addAll((Collection<? extends Condition>)newValue);
        return;
      case GamesPackage.INTERACTION__CONDITIONS_END:
        getConditionsEnd().clear();
        getConditionsEnd().addAll((Collection<? extends Condition>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case GamesPackage.INTERACTION__NAME:
        setName(NAME_EDEFAULT);
        return;
      case GamesPackage.INTERACTION__PROP:
        getProp().clear();
        return;
      case GamesPackage.INTERACTION__CONDITIONS_BEGIN:
        getConditionsBegin().clear();
        return;
      case GamesPackage.INTERACTION__CONDITIONS_END:
        getConditionsEnd().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case GamesPackage.INTERACTION__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case GamesPackage.INTERACTION__PROP:
        return prop != null && !prop.isEmpty();
      case GamesPackage.INTERACTION__CONDITIONS_BEGIN:
        return conditionsBegin != null && !conditionsBegin.isEmpty();
      case GamesPackage.INTERACTION__CONDITIONS_END:
        return conditionsEnd != null && !conditionsEnd.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} //InteractionImpl
