/**
 * generated by Xtext 2.10.0
 */
package fr.enseeiht.gls.projet404.games.impl;

import fr.enseeiht.gls.projet404.games.GamesPackage;
import fr.enseeiht.gls.projet404.games.ItemInSomething;
import fr.enseeiht.gls.projet404.games.Knowledge;
import fr.enseeiht.gls.projet404.games.Path;
import fr.enseeiht.gls.projet404.games.People;
import fr.enseeiht.gls.projet404.games.Place;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.EObjectResolvingEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Place</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link fr.enseeiht.gls.projet404.games.impl.PlaceImpl#getName <em>Name</em>}</li>
 *   <li>{@link fr.enseeiht.gls.projet404.games.impl.PlaceImpl#getKnowledges <em>Knowledges</em>}</li>
 *   <li>{@link fr.enseeiht.gls.projet404.games.impl.PlaceImpl#getPeople <em>People</em>}</li>
 *   <li>{@link fr.enseeiht.gls.projet404.games.impl.PlaceImpl#getPaths <em>Paths</em>}</li>
 *   <li>{@link fr.enseeiht.gls.projet404.games.impl.PlaceImpl#getObjects <em>Objects</em>}</li>
 * </ul>
 *
 * @generated
 */
public class PlaceImpl extends MinimalEObjectImpl.Container implements Place
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getKnowledges() <em>Knowledges</em>}' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getKnowledges()
   * @generated
   * @ordered
   */
  protected EList<Knowledge> knowledges;

  /**
   * The cached value of the '{@link #getPeople() <em>People</em>}' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPeople()
   * @generated
   * @ordered
   */
  protected EList<People> people;

  /**
   * The cached value of the '{@link #getPaths() <em>Paths</em>}' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPaths()
   * @generated
   * @ordered
   */
  protected EList<Path> paths;

  /**
   * The cached value of the '{@link #getObjects() <em>Objects</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getObjects()
   * @generated
   * @ordered
   */
  protected EList<ItemInSomething> objects;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PlaceImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GamesPackage.Literals.PLACE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GamesPackage.PLACE__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Knowledge> getKnowledges()
  {
    if (knowledges == null)
    {
      knowledges = new EObjectResolvingEList<Knowledge>(Knowledge.class, this, GamesPackage.PLACE__KNOWLEDGES);
    }
    return knowledges;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<People> getPeople()
  {
    if (people == null)
    {
      people = new EObjectResolvingEList<People>(People.class, this, GamesPackage.PLACE__PEOPLE);
    }
    return people;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Path> getPaths()
  {
    if (paths == null)
    {
      paths = new EObjectResolvingEList<Path>(Path.class, this, GamesPackage.PLACE__PATHS);
    }
    return paths;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<ItemInSomething> getObjects()
  {
    if (objects == null)
    {
      objects = new EObjectContainmentEList<ItemInSomething>(ItemInSomething.class, this, GamesPackage.PLACE__OBJECTS);
    }
    return objects;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case GamesPackage.PLACE__OBJECTS:
        return ((InternalEList<?>)getObjects()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case GamesPackage.PLACE__NAME:
        return getName();
      case GamesPackage.PLACE__KNOWLEDGES:
        return getKnowledges();
      case GamesPackage.PLACE__PEOPLE:
        return getPeople();
      case GamesPackage.PLACE__PATHS:
        return getPaths();
      case GamesPackage.PLACE__OBJECTS:
        return getObjects();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case GamesPackage.PLACE__NAME:
        setName((String)newValue);
        return;
      case GamesPackage.PLACE__KNOWLEDGES:
        getKnowledges().clear();
        getKnowledges().addAll((Collection<? extends Knowledge>)newValue);
        return;
      case GamesPackage.PLACE__PEOPLE:
        getPeople().clear();
        getPeople().addAll((Collection<? extends People>)newValue);
        return;
      case GamesPackage.PLACE__PATHS:
        getPaths().clear();
        getPaths().addAll((Collection<? extends Path>)newValue);
        return;
      case GamesPackage.PLACE__OBJECTS:
        getObjects().clear();
        getObjects().addAll((Collection<? extends ItemInSomething>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case GamesPackage.PLACE__NAME:
        setName(NAME_EDEFAULT);
        return;
      case GamesPackage.PLACE__KNOWLEDGES:
        getKnowledges().clear();
        return;
      case GamesPackage.PLACE__PEOPLE:
        getPeople().clear();
        return;
      case GamesPackage.PLACE__PATHS:
        getPaths().clear();
        return;
      case GamesPackage.PLACE__OBJECTS:
        getObjects().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case GamesPackage.PLACE__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case GamesPackage.PLACE__KNOWLEDGES:
        return knowledges != null && !knowledges.isEmpty();
      case GamesPackage.PLACE__PEOPLE:
        return people != null && !people.isEmpty();
      case GamesPackage.PLACE__PATHS:
        return paths != null && !paths.isEmpty();
      case GamesPackage.PLACE__OBJECTS:
        return objects != null && !objects.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} //PlaceImpl
