/*
 * generated by Xtext 2.10.0
 */
package fr.enseeiht.gls.projet404.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractGamesScopeProvider extends DelegatingScopeProvider {
}
